baseurl: "" # the subpath of your site, e.g. /blog
title: "Daniel Taborda"
description: "Daniel Taborda"

remote_theme: pages-themes/slate@v0.2.0

plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

theme: jekyll-theme-slate

google_analytics: 1234

keep_files: [CNAME, .git]

gems:
- jekyll-github-metadata
- jekyll-redirect-from
-     

markdown: kramdown
